sudo: required
language: python
python: 3.6
services:
- docker

cache:
  directories:
  - docker-cache

before_script:
- |
  filename=docker-cache/saved_images.tar
  if [[ -f "$filename" ]]; then
     docker load < "$filename";
  else
    mkdir -p docker-cache
    docker pull bgruening/galaxy-stable:19.09
    docker save -o "$filename" bgruening/galaxy-stable:19.09
  fi

script:
- bash run_tests_with_containers.sh


deploy:
  provider: pypi
  user: __token__
  password:
    secure: l56LHAWCd4LeG/+cHanG6bTavnnr6BwWwqD3KS4Dh2IzsSoeKimvUcRbF7A8ZbOGNkIQrStnyR+kn85DLtNPdFbdaBaAbWHHYj/2IkxdC5kTowCZkzPSWBJi23xNJzFiwtxIPkAhh1jWb9cKEIzM8PvUM3jOC7h2K7zYYt+U9Vnw8ur/zCo/BIFy+gaTllceoywwXbq3Q530PA4MZsrbuz7/Ik7Y9n1eLQv/JaZJ+Yx/FNzsL4EavzCngXY335ga7OHaS3xehzp3FriiDzoElI15d5N0ChI6pHgEu2VHX3IixZB9Cef7T2Vmpu3tV6G5bcQ6jGetGhajr1U2Kw+qXSuMzliekIqqKy0eWSenVhJoEWCwE25MaOeu+58jArlvtywaEcxWlRMR7MyekPDWqpqvc4NROJYQ2UND0LsNrtcN832j6mGxo650sE3JGIqayxFTuM/hVhGyqw/nvjAPYC/2hI+xIpldC4jfpQ0gms4HE6J7EqFsPRVBz5bGiYkqcZQCJXomnUcH9FWT33MqsZwB2twYVKjorYY8c5qWnC2thWK6whgdeS+/MD62LBBKzXaLtfSLihSBkO2UB2EdbsAw9j+5nIBPJJWJkmYh4yezE98A0PraI8nx2rC6crtBwm8bk19a4YOHEtnhKil/CinNG6+o4NEdzuzZzE4yxwM=
  distributions: sdist bdist_wheel
  on:
    branch: master

